name: Web Scraping Action

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */4 * * *"

jobs:
    web_scraping:
        runs-on: ubuntu-latest
        container:
            image: node:18
            options: --init

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_PAT }}

            - name: Install Chrome dependencies
              run: |
                  apt-get update
                  apt-get install -y \
                      libnss3 \
                      libnspr4 \
                      libatk1.0-0 \
                      libatk-bridge2.0-0 \
                      libcups2 \
                      libdrm2 \
                      libxkbcommon0 \
                      libxcomposite1 \
                      libxdamage1 \
                      libxfixes3 \
                      libxrandr2 \
                      libgbm1 \
                      libasound2 \
                      libpango-1.0-0 \
                      libcairo2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Run scraper script
              run: npm start

            - name: Commit changes
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add patch_version.json
                  git commit -m "Update patch_version.json" || echo "No changes to commit"
                  git push https://${{secrets.GH_PAT}}@github.com/9kosho/TFT-latest-patch-timestamp.git main
