name: 1. Web Scraping Action

on:
    workflow_dispatch: # Manual trigger
    schedule:
        # Run the scraper at 6:00 AM, 12:00 PM, 6:00 PM, and 12:00 AM PST
        - cron: "0 8,14,20,2 * * *"

jobs:
    web_scraping:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_PAT }}

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Run scraper script
              run: npm start

            - name: Commit changes
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add patch_version.json
                  git commit -m "Update patch_version.json" || echo "No changes to commit"
                  git push https://${{secrets.GH_PAT}}@github.com/9kosho/TFT-latest-patch-timestamp.git main
