name: 1. Web Scraping Action

on:
    workflow_dispatch: # Manual trigger
    schedule:
        # Run the scraper every day at 6:00 AM and 6:00 PM PST
        - cron: "0 2,14 * * *"

jobs:
    web_scraping:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_PAT }}

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Run scraper script
              run: node src/main-scraper.js

            # Check if there are changes
            - name: Check for changes
              id: check_changes
              run: |
                  git diff --exit-code || echo "changes::true" >> $GITHUB_ENV
              continue-on-error: true

            # Only run the next steps if there were changes
            - name: Commit changes
              if: env.changes == 'true'
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add patch_version.json
                  git commit -m "Update patch_version.json"
                  git push https://${{secrets.GH_PAT}}@github.com/9kosho/TFT-latest-patch-timestamp.git main
